// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrjlhw2arBjd0GwmEdIo8AoUOkiMM6_0o',
    appId: '1:845944344196:web:3dcbfe99872b1a5805bcd1',
    messagingSenderId: '845944344196',
    projectId: 'yonigames-30515',
    authDomain: 'yonigames-30515.firebaseapp.com',
    storageBucket: 'yonigames-30515.firebasestorage.app',
    measurementId: 'G-DVS9P855ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQQoXx7fiIcWpZ-Uohuo2TgAtSOjxrTo',
    appId: '1:845944344196:android:66cb21e1038a6edc05bcd1',
    messagingSenderId: '845944344196',
    projectId: 'yonigames-30515',
    storageBucket: 'yonigames-30515.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxg4GZImYu9HtlHhyzqg36bnBF0guG5ms',
    appId: '1:845944344196:ios:2a3e8f747c31674305bcd1',
    messagingSenderId: '845944344196',
    projectId: 'yonigames-30515',
    storageBucket: 'yonigames-30515.firebasestorage.app',
    iosBundleId: 'com.example.yonigamesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxg4GZImYu9HtlHhyzqg36bnBF0guG5ms',
    appId: '1:845944344196:ios:2a3e8f747c31674305bcd1',
    messagingSenderId: '845944344196',
    projectId: 'yonigames-30515',
    storageBucket: 'yonigames-30515.firebasestorage.app',
    iosBundleId: 'com.example.yonigamesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrjlhw2arBjd0GwmEdIo8AoUOkiMM6_0o',
    appId: '1:845944344196:web:6b3d3ef0777a2bf305bcd1',
    messagingSenderId: '845944344196',
    projectId: 'yonigames-30515',
    authDomain: 'yonigames-30515.firebaseapp.com',
    storageBucket: 'yonigames-30515.firebasestorage.app',
    measurementId: 'G-YZ072ZRM4H',
  );
}
